### ISSUE TITLE
this is a very difficlut question

### ISSUE THREAD

**Issue by LanHuang025** [luftaquila/toolsets#1]
https://github.com/nk-o/flickr-justified-gallery
this link links to a library which can display photo as a gallery ,but i dont know how to append image by the 
method he gives me,i had saw the issue you left on that,i think might you will give the answer of my question
to me,i`m a Chinese and English is not very well.
In the end,think you very much.

**Comment by LanHuang025** [comment]
[``](https://github.com/nk-o/flickr-justified-gallery)

**Comment by LanHuang025** [comment]
https://github.com/nk-o/flickr-justified-gallery

**Comment by LanHuang025** [comment]
https://github.com/nk-o/flickr-justified-gallery

**Comment by luftaquila** [comment]
Then you must issue a problem there, not in my personal no-related repository. This is very rude behavior and how not to use git properly.
